### ISSUE TITLE
Unable to add items to my collection

### ISSUE THREAD

**Issue by SlumberDemon** [tbdsux/zeta-library#2]
When I click add item on my collection I can't add any item, It only lets me copy, search or press done
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/72651859/204516254-45e07bc2-a51e-47fb-bbd5-7250c387a68f.png">

**Comment by SlumberDemon** [comment]
First of all that is way to complicated and second it didn't work

**Comment by SlumberDemon** [comment]
> Hello, sorry for late reply, I was pretty busy. I'm sorry that I forgot to add a guide on how to add items to collections.
> 
> How to add items:
> 
> * Search and select the items you want to add
> * You can preview your selected items using the left button from `Done`
> * Click `Done` once you are done

First of all that is way to complicated and second it didn't work

**Comment by TheBoringDude** [comment]
Hmmm.., that's weird, it working perfectly fine for me. 

I'll try to change how it works so adding items would be direct from a button.

**Comment by SlumberDemon** [comment]
> Hmmm.., that's weird, it working perfectly fine for me.
> 
> I'll try to change how it works so adding items would be direct from a button.

Thanks
